In [2]:
import numpy as np

In [143]:
# arange function
r = np.arange(0,21)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [144]:
# zeros function
q = np.zeros(10)
q

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [145]:
# ones function
p = np.ones(10)
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [146]:
# full function
o = np.full(10,3.14)
o

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [147]:
# Adding step value
n = np.arange(0,50,4)
n


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [148]:
# adding matrix inside arange using reshape function
m = np.arange(0,9).reshape(3,3)
m


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#The difference between list and array:
#We are dealing with array where we can use only same type of elements, whereas list can contain any datatype
#list computation will take more time than array as it deals with homogenous data
#Array is used only for storing similar datatypes

In [44]:
# converting core list to numpy Array
lst = list(range(0,10))        # explicit list creation
l2 = [x for x in range(0,10)]  # list comprehension
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
l3 = [str(x) for x in l2]      # converting int to str
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [46]:
l4 = [x**2 for x in l2]        # squaring l2
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [39]:
arr?


Type:        ndarray
String form:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Length:      3
File:        c:\users\roshni golani\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of create

## Array Library

In [41]:
import array as a

In [47]:
ar = a.array('i',l2) # 'i' is dtype which represents integer
ar1 = a.array('i',[x**2 for x in l2])
ar1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [48]:
nparr = np.array([x+3 for x in l2])
nparr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
# explicitly telling to store dtype as float
nparr1 = np.array([x for x in l2],dtype=float) # same change float to str to make string data type
nparr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
nparr2 = np.float64([x for x in l2])
nparr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
# 2-D lsit or Nested list
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [52]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [53]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [5]:
nparr3 = np.zeros((10,10))
nparr3[1:-1,8:-1]=1
nparr3[1:-1,7:-1]=1
nparr3[1:-1,6:-1]=1
nparr3[1:-1,5:-1]=1
nparr3[1:-1,4:-1]=1
nparr3[1:-1,3:-1]=1
nparr3[1:-1,2:-1]=1
nparr3[1:-1,1:-1]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
import numpy as np

In [6]:
nparr3[1:9,1:9]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr = np.full((3,3),3.14)
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [8]:
arr = np.ones((3,3))
arr[:]=3.14
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [9]:
# eye() function for identity matrix
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [10]:
arr5 = np.eye(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
arr7 = np.matrix.transpose(arr5)
arr7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
arr8 = np.full((6,6),64)
arr8

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

### Linspace - Lineraly spaced elements

In [13]:
np.linspace(0,1,5) #starting val , ending val , no. of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [15]:
# Random Function - returns value between 0-1
np.random.random((3,3))

array([[0.82371363, 0.27328493, 0.44352316],
       [0.82418403, 0.70331692, 0.13306147],
       [0.73378086, 0.20964355, 0.47208171]])

In [16]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [17]:
np.random.normal(0,1,10) #values with mean 0 and std 1

array([-0.41903682,  0.25632528, -1.26182318, -0.22246373,  2.04843963,
        1.21745689, -0.0481421 ,  1.73168022, -2.60247176, -0.88775747])

In [18]:
np.random.normal(0,1,(4,5))

array([[ 1.78474972, -0.34320652,  0.86784573,  2.17381808,  1.82710371],
       [ 1.27915425, -2.06651888,  1.54576012, -0.35600191, -0.64157988],
       [ 0.15604773, -0.44634165, -0.13118204, -1.05678676,  0.49553079],
       [-0.07585418,  0.05470798, -0.84900626, -1.8093857 , -0.24422223]])

In [19]:
np.random.randint(50,100,30)

array([68, 62, 51, 99, 72, 75, 65, 51, 93, 98, 92, 89, 56, 66, 57, 74, 65,
       94, 57, 96, 96, 81, 89, 76, 73, 54, 98, 81, 97, 69], dtype=int32)

In [20]:
np.random.randn?

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

### Operations on Numpy Array

In [21]:
arr9 = np.random.randint(10,100,(20,2))
arr9

array([[13, 19],
       [25, 48],
       [45, 20],
       [31, 55],
       [81, 61],
       [36, 79],
       [83, 25],
       [21, 20],
       [51, 31],
       [86, 67],
       [94, 33],
       [37, 26],
       [32, 10],
       [76, 68],
       [33, 80],
       [32, 39],
       [10, 91],
       [13, 77],
       [40, 32],
       [84, 59]], dtype=int32)

In [22]:
arr9.ndim # to check number of dimension of an array

2

In [23]:
arr9.size # to check the size of an array

40

In [24]:
arr9.shape # to check the shape inclusive of both dimension and size

(20, 2)

In [25]:
arr9.dtype # returns datatype of an array

dtype('int32')

### Array Indexing

In [26]:
np.random.seed(101)
ar = np.random.randint(1,10,10)
ar

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9], dtype=int32)

In [27]:
ar[:4]

array([2, 7, 8, 9], dtype=int32)

In [28]:
ar[-1]

np.int32(9)

In [29]:
ar[5]

np.int32(9)

In [30]:
ar[1]=45

## Slicing And Indexing for 2D Array

In [7]:
np.random.randint(0,100,36)

array([54,  9, 24, 47, 21, 47, 57, 90, 65, 24, 52, 74, 67, 63,  4, 92, 84,
       19, 53, 85,  3, 97, 48, 75, 82, 13,  5, 78, 72, 68, 73,  7, 92, 32,
       90, 25], dtype=int32)

In [8]:
#3D
ar=np.arange(0,27).reshape(3,3,3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
#2D
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#linear
np.arange(0,3).reshape(3)

array([0, 1, 2])

In [11]:
arr=[1,2,3,4,5,6]
arr

[1, 2, 3, 4, 5, 6]

In [12]:
arr[:3]

[1, 2, 3]

In [13]:
#gives array beginning from position 2 to 6, skipping to every 2 value
arr[2:6:2]

[3, 5]

In [14]:
arr[::3]

[1, 4]

In [15]:
arr[::2]

[1, 3, 5]

In [16]:
#order of the array is reversed
arr[::-1]

[6, 5, 4, 3, 2, 1]

In [17]:
arr[::-2]

[6, 4, 2]

In [18]:
a=np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
a2=np.random.randint(0,16,(5,5))
a2

array([[12, 11,  0,  2,  8],
       [15, 14,  0,  3,  4],
       [14,  6,  7,  8,  5],
       [ 1,  8, 10, 10, 11],
       [ 3, 15,  8,  8,  9]], dtype=int32)

In [20]:
#gives elements from the 2D array in row 0 from 1 to 4th element
#note that the indexing for rows and columns start from 0
a2[0,1:4]

array([11,  0,  2], dtype=int32)

In [21]:
a2[0,1]

np.int32(11)

In [22]:
a2[2,1]

np.int32(6)

In [23]:
#whlie giving range the 2nd element is an explicit value, hence add 1 to the required position for second element
#like here for accessing the 1st element in row you give 2 
a2[0:2,1]

array([11, 14], dtype=int32)

In [24]:
a2[0:3,1]

array([11, 14,  6], dtype=int32)

In [25]:
a2[0:3,1:3]

array([[11,  0],
       [14,  0],
       [ 6,  7]], dtype=int32)

In [26]:
a2[0:3,0:3]

array([[12, 11,  0],
       [15, 14,  0],
       [14,  6,  7]], dtype=int32)

In [27]:
a2[:3,:3]

array([[12, 11,  0],
       [15, 14,  0],
       [14,  6,  7]], dtype=int32)

In [28]:
a2[2:4,3:5]

array([[ 8,  5],
       [10, 11]], dtype=int32)

In [29]:
a2[::2]    #gives entire matrix skipping every 2nd row

array([[12, 11,  0,  2,  8],
       [14,  6,  7,  8,  5],
       [ 3, 15,  8,  8,  9]], dtype=int32)

In [30]:
a2

array([[12, 11,  0,  2,  8],
       [15, 14,  0,  3,  4],
       [14,  6,  7,  8,  5],
       [ 1,  8, 10, 10, 11],
       [ 3, 15,  8,  8,  9]], dtype=int32)

In [31]:
a2[:,:]

array([[12, 11,  0,  2,  8],
       [15, 14,  0,  3,  4],
       [14,  6,  7,  8,  5],
       [ 1,  8, 10, 10, 11],
       [ 3, 15,  8,  8,  9]], dtype=int32)

In [32]:
a2[::,::2]

array([[12,  0,  8],
       [15,  0,  4],
       [14,  7,  5],
       [ 1, 10, 11],
       [ 3,  8,  9]], dtype=int32)

In [33]:
#gives reverse of matrix
a2[::-1,::-1]

array([[ 9,  8,  8, 15,  3],
       [11, 10, 10,  8,  1],
       [ 5,  8,  7,  6, 14],
       [ 4,  3,  0, 14, 15],
       [ 8,  2,  0, 11, 12]], dtype=int32)

In [34]:
a2

array([[12, 11,  0,  2,  8],
       [15, 14,  0,  3,  4],
       [14,  6,  7,  8,  5],
       [ 1,  8, 10, 10, 11],
       [ 3, 15,  8,  8,  9]], dtype=int32)

In [59]:
na2=a2[3:5,3:5]
na2

array([[10, 11],
       [ 8,  9]], dtype=int32)

## SHALLOW COPY

In [64]:
na2[1,1]=19
na2

array([[10, 11],
       [ 8, 19]], dtype=int32)

In [65]:
a2
#note that change in sub-array is applied to the original array too and same for viceversa

array([[12, 11,  0,  2,  8],
       [15, 14,  0,  3,  4],
       [14,  6,  7,  8,  5],
       [ 1,  8, 10, 10, 11],
       [ 3, 15,  8,  8, 19]], dtype=int32)

In [67]:
a2[2,1]=16
na2

array([[10, 11],
       [ 8, 19]], dtype=int32)

## DEEP COPY

In [69]:
ia2=a2[:2,:2].copy()
ia2

array([[12, 11],
       [15, 14]], dtype=int32)

In [71]:
ia2[1,1]=4
a2
#deep copy does not change the original array

array([[12, 11,  0,  2,  8],
       [15, 14,  0,  3,  4],
       [14, 16,  7,  8,  5],
       [ 1,  8, 10, 10, 11],
       [ 3, 15,  8,  8, 19]], dtype=int32)

## 2D to 1D CONVERSION

In [76]:
import numpy as np

In [78]:
rr=np.array([1,2,3])
rr

array([1, 2, 3])

In [80]:
rr.reshape(3,1)
#converts rows to column

array([[1],
       [2],
       [3]])

In [82]:
rs=np.arange(0,9)
rs

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
rs.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
rs.reshape(1,9)
#1st way to convert 2D to 1D array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [86]:
rs.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
rs.ravel
rs
#2nd way

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
rs.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
rs.flatten
rs
#3rd way

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
flatten?

Object `ar.flatten` not found.


In [96]:
np.ravel?

Signature:       np.ravel(a, order='C')
Call signature:  np.ravel(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function ravel at 0x00000216FFD044A0>
File:            c:\users\roshni golani\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return a contiguous flattened array.

A 1-D array, containing the elements of the input, is returned.  A copy is
made only if needed.

As of NumPy 1.10, the returned array will have the same type as the input
array. (for example, a masked array will be returned for a masked array
input)

Parameters
----------
a : array_like
    Input array.  The elements in `a` are read in the order specified by
    `order`, and packed as a 1-D array.
order : {'C','F', 'A', 'K'}, optional

    The elements of `a` are read using this index order. 'C' means
    to index the elements in row-major, C-style order,
    with the last axis index changing fastest, back to the first
    axis ind

In [101]:
rs[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## CONCATENATION FOR JOINING OF TWO ARRAYS 

In [103]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [27]:
n=np.array([2,3,4,5])
n

array([2, 3, 4, 5])

In [28]:
m=np.array([5,6,7,2])
m

array([5, 6, 7, 2])

In [29]:
n=n.reshape(2,2)
n

array([[2, 3],
       [4, 5]])

In [30]:
m=m.reshape(2,2)
m

array([[5, 6],
       [7, 2]])

In [31]:
np.concatenate([n,m])

array([[2, 3],
       [4, 5],
       [5, 6],
       [7, 2]])

In [32]:
o=np.concatenate([n,m],axis=1) #axis to specify rows
o

array([[2, 3, 5, 6],
       [4, 5, 7, 2]])

In [33]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x00000235B1804F40>
File:            c:\users\roshni golani\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same

In [44]:
import numpy as np
x=np.array([1,2,3])
x

array([1, 2, 3])

In [47]:
grid=np.array([9,8,7,5,4,6]).reshape(2,3)
grid

array([[9, 8, 7],
       [5, 4, 6]])

In [48]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [5, 4, 6]])

In [50]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [58]:
x=np.array([1,2,3])
grid.flatten()

array([9, 8, 7, 5, 4, 6])

In [63]:
y=np.array([10,11,12,13])
y[:,np.newaxis]

array([[10],
       [11],
       [12],
       [13]])

In [64]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x00000235B195B380>
File:            c:\users\roshni golani\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

    - ary[:2]
    - ary[2:3]
    - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an

In [68]:
r=np.array([1,2,3,4,5])
r

array([1, 2, 3, 4, 5])

In [69]:
np.split(r,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [70]:
# the array is divided into parts like :1:2:4:
np.split(r,[1,2,4])

[array([1]), array([2]), array([3, 4]), array([5])]

In [71]:
# the array is divided into parts like :1:2:
np.split(r,[1,2])

[array([1]), array([2]), array([3, 4, 5])]

In [74]:
rs=np.arange(1,9).reshape(2,4)
rs

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
# vsplit vertically splits the array equallyinto parts as mentioned
np.vsplit(rs,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [78]:
# hsplit horizontally splits the array into equal parts as mentioned
np.hsplit(rs,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [79]:
# splits the array into :2:3: parts
np.hsplit(rs,[2,3])

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

## Universal Functions

In [80]:
rs

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
#gives sum for all the elements
np.sum(rs)

np.int64(36)

In [82]:
#gives sum for each column
np.sum(rs,0)

array([ 6,  8, 10, 12])

In [83]:
#gives sum for each row
np.sum(rs,1)

array([10, 26])

In [85]:
i=-5
np.abs(i)
#abs gives the absolute value

np.int64(5)

In [86]:
np.std(rs)
#std gives standard deviation

np.float64(2.29128784747792)

In [87]:
np.var(rs)
#var gives variance

np.float64(5.25)

In [89]:
np.prod(rs)
#prod gives the product

np.int64(40320)

In [90]:
np.mean(rs)

np.float64(4.5)

In [91]:
np.median(rs)

np.float64(4.5)

In [92]:
np.max(rs)

np.int64(8)

In [93]:
np.min(rs)

np.int64(1)

## Numpy Exercise 1

In [2]:
# 1.Import Numpy as np
import numpy as np

In [9]:
# 2.Create an array of 10 zeroes
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 3.Create an array of 10 ones
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# 4.Create an array of the integers from 10 to 50
c=np.arange(10,51)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [21]:
# 5.Create an array of all the even integers from 10 to 50
d=np.arange(10,51,2)
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [24]:
# 6.Create a 3X3 matrix with values ranging from 0 to 1
e=np.arange(0,9)
e.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
# 7.Create a 3X3 identity matrix
x=np.eye(3,3)
x


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# 8. use NumPy to generate a random number between 0 to 1 
np.random.random(1)

array([0.60354842])

In [69]:
# 9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution
ar=np.random.randint(0,24,25)
ar

array([ 5, 14,  7,  5,  4, 20, 23,  3, 15,  2,  3, 18, 13, 14,  3, 14,  5,
       22, 22, 21, 21, 17, 23, 11,  4], dtype=int32)

In [77]:
# 10. Create a matrix of 10x10 linearly spaced elements from 0.01 to 1  
np.linspace(0.01,1,100).reshape(10,10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [78]:
# 11. Create an array of 20 linearly spaced points between 0 and 1 
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [91]:
# 12.Create a 5x5 matrix as  
# array([[ 1,  2,  3,  4,  5], 
#        [ 6,  7,  8,  9, 10], 
#        [11, 12, 13, 14, 15], 
#        [16, 17, 18, 19, 20], 
#        [21, 22, 23, 24, 25]]) 
#  find following using slicing
a=np.arange(1,26).reshape(5,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
# # a. array([[12, 13, 14, 15], 
#             [17, 18, 19, 20], 
#             [22, 23, 24, 25]]) 
a[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [93]:
# b. 20 
a[3,4]

np.int64(20)

In [97]:
# c.array([[ 2], 
# [ 7], 
# [12]])
a[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [98]:
#d.array([21, 22, 23, 24, 25])
a[4,]

array([21, 22, 23, 24, 25])

In [100]:
# e.array([[16, 17, 18, 19, 20], 
# [21, 22, 23, 24, 25]])
e=np.arange(16,26).reshape(2,5)
e

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [109]:
# 13. Get sum of all values in matrix
np.sum(e)

np.int64(205)

In [110]:
# 14. Get sum of all the columns in matrix 
np.sum(e,axis=0)

array([37, 39, 41, 43, 45])

In [114]:
# 15. Get Standard deviation , variance , minimum, maximum from matrix  row wise
np.std(e,axis=1)

array([1.41421356, 1.41421356])

In [115]:
np.var(e,axis=1)

array([2., 2.])

In [116]:
np.min(e,axis=1)

array([16, 21])

In [117]:
np.max(e,axis=1)

array([20, 25])

In [121]:
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__a

In [120]:
# 16. create 2 d matrix with all border values nan and
m=np.full((4,4),np.nan)
m[1:3,1:3]=1
m

array([[nan, nan, nan, nan],
       [nan,  1.,  1., nan],
       [nan,  1.,  1., nan],
       [nan, nan, nan, nan]])

## NUMPY EXERCISE 2

In [149]:
# 1. Create 1-D, 2-D and 3-D numpy array 
a1=np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
a2=np.arange(1,11).reshape(2,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [155]:
a3=np.arange(1,28).reshape(3,3,3)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [156]:
# 2. Print data type of array.
a1.dtype

dtype('int64')

In [159]:
# 3. Print shape and dimensions of all the three different array. 
a1.shape

1

In [160]:
a2.shape

(2, 5)

In [161]:
a3.shape

(3, 3, 3)

In [162]:
a1.ndim

1

In [163]:
a2.ndim

2

In [164]:
a3.ndim

3

In [167]:
# 4. Create another 1-D array of 12 elements filled with zero 
a4=np.zeros(12)
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [170]:
# 5. Create another 2-D array elements filled with ones. 
a5=np.ones([4,4])
a5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [172]:
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.
a6=np.random.randint(0,100,20)
a6

array([24, 20, 64, 52, 60, 47, 29, 60, 53, 11, 40, 91, 45, 97, 24, 36, 38,
        9, 52, 67], dtype=int32)

In [173]:
# 7. Sort the above array in ascending and descending order. 
a7=np.sort(a6)
a7

array([ 9, 11, 20, 24, 24, 29, 36, 38, 40, 45, 47, 52, 52, 53, 60, 60, 64,
       67, 91, 97], dtype=int32)

In [178]:
a8=np.sort(a6)[::-1]
a8

array([97, 91, 67, 64, 60, 60, 53, 52, 52, 47, 45, 40, 38, 36, 29, 24, 24,
       20, 11,  9], dtype=int32)

In [179]:
# 8. Create a copy of sorted array to another variable by deep copying. 
a9=a8[::].copy()
a9

array([97, 91, 67, 64, 60, 60, 53, 52, 52, 47, 45, 40, 38, 36, 29, 24, 24,
       20, 11,  9], dtype=int32)

In [181]:
# 9. Create 2-D array of 5x5 which is an identity matrix and then convert 1D . 
a=np.eye(5,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [182]:
a.reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [192]:
# 10. Create 2-D array of 3x3. Add one more row to it.
b=np.arange(0,9).reshape(3,3)
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
c=np.arange(9,12).reshape(1,3)
c

array([[ 9, 10, 11]])

In [187]:
d=np.concatenate([b,c])
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [196]:
# 11. Split above array created vertically and horizontally.
k=np.vsplit(d,4)
k

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [189]:
m=np.hsplit(d,3)
m

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [198]:
# 12. Create 4x4 identity matrix. Add 4 to each element. 
n=np.eye(4,4)
n

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [199]:
o=4
p=o+n
p

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [201]:
# 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal’s). 
x=np.random.random(5)
x


array([0.59120021, 0.93734815, 0.17446733, 0.36552738, 0.19451465])

In [202]:
r=np.ceil(x)
r

array([1., 1., 1., 1., 1.])

In [203]:
t=np.round(x,2)
t

array([0.59, 0.94, 0.17, 0.37, 0.19])

In [204]:
s=np.floor(x)
s

array([0., 0., 0., 0., 0.])

In [205]:
# 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise. 
y=np.arange(5,30).reshape(5,5)
y

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [206]:
np.min(y,axis=0)

array([5, 6, 7, 8, 9])

In [207]:
np.max(y,axis=0)

array([25, 26, 27, 28, 29])

In [208]:
np.var(y,axis=0)

array([50., 50., 50., 50., 50.])

In [209]:
np.std(y,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [210]:
# 15. Create a null vector of size 10 with 6th value filled with 200. 
z=np.full((10),(np.nan))
z


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [211]:
z[5]=200
z

array([ nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan,  nan])

In [212]:
# 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.
u=np.arange(100,151)
u


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [213]:
# 17. Reverse the above vector.
u[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [214]:
# 18. Create a 5x5 matrix with values ranging from 0-24 using some function.
v=np.arange(0,25).reshape(5,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [215]:
# 19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8] 
e=np.array([1,0,2,0,0,4,0,8])
e

array([1, 0, 2, 0, 0, 4, 0, 8])

In [216]:
f=np.nonzero(e)
f

(array([0, 2, 5, 7]),)

In [217]:
# 20. Create a 10x10 matrix with 1 on the borders and 0 inside. 
q=np.ones(100).reshape(10,10)
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [218]:
q[1:9,1:9]=0
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [219]:
# 21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern. 
o=np.zeros([8,8])
o

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [220]:
o[::2,::2]=1
o[1::2,1::2]=1
o

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [222]:
# 22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction
x=np.random.randint(1,20,[3,3])
x

array([[11,  1, 12],
       [19,  8, 14],
       [13,  3,  9]], dtype=int32)

In [223]:
y=np.random.randint(21,40,[3,3])
y

array([[38, 22, 23],
       [37, 39, 23],
       [36, 27, 31]], dtype=int32)

In [224]:
z=x+y
z

array([[49, 23, 35],
       [56, 47, 37],
       [49, 30, 40]], dtype=int32)

In [225]:
a=x-y
a

array([[-27, -21, -11],
       [-18, -31,  -9],
       [-23, -24, -22]], dtype=int32)

In [226]:
b=x*y
b

array([[418,  22, 276],
       [703, 312, 322],
       [468,  81, 279]], dtype=int32)

In [227]:
np.random.seed(10)
b=np.random.random(10)
b

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [ ]:
print("")